import { Component } from '@angular/core';
import { Pipe, PipeTransform } from '@angular/core';

@Component({
  selector: 'app-pipes',
  templateUrl: './pipes.component.html',
  styleUrls: ['./pipes.component.css']
})
export class PipesComponent {
 Brand: string = "";
  proarray = [
    { Image:'./assets/c1.webp',
      Brand:'Full Stack Development',
      Description:'The art of seamlessly combining front-end and back-end technologies to create web applications .',
      Time: '6 Month',
      Rate: 5.0,
      
    },
    { Image:'./assets/c2.webp',
    Brand:'Digital Marketing',
    Description:'Digital marketing is the strategic use of online channels to promote products or services, build brand awareness, and engage with target audiences.',
    Time: '1 Month',
    Rate: 4.8,
    },
    { Image:'./assets/c3.webp',
    Brand:'Machine Learning',
    Description:'Machine Learning is a field of study that enables computers to learn from data and make predictions or decisions without being explicitly programmed.',
    Time: '5 Month',
    Rate: 4.5,
    },
    { Image:'./assets/c4.webp',
    Brand:'Python',
    Description:'Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant rule. ',
    Time: '2 Month',
    Rate: 4.0,
    Link: "/python",
    },
    { Image:'./assets/c5.webp',
    Brand:'C And C++',
    Description:'C is a procedural programming language known for its efficiency and close-to-hardware control, C++ is a versatile object-oriented programming language that extends the capabilities of C.',
    Time: '1 Month',
    Rate: 4.9,
    },
    { Image:'./assets/c6.png',
    Brand:'Data Science',
    Description:'Data science is the study of data to extract meaningful insights for business.',
    Time: '5 Month',
    Rate: 4.6,
    },
    { Image:'./assets/c7.png',
    Brand:'Android App',
    Description:'Android is a mobile operating system based on a modified version of the Linux kernel and other open-source software, designed for mobile devices.',
    Time: '8 Month',
    Rate: 4.7,
    },
    { Image:'./assets/c8.png',
    Brand:'Stock Market',
    Description:'A stock market, equity market, or share market is the aggregation of buyers and sellers of stocks, which represent ownership claims on businesses.',
    Time: '15 Days',
    Rate: 5.0,
    },
    { Image:'./assets/c9.png',
    Brand:'Auto CAD',
    Description:'AutoCAD is a professional computer-aided design (CAD) software used for creating precise 2D and 3D drawings and models.',
    Time: '3 Month',
    Rate: 4.5,
    },
    { Image:'./assets/c10.png',
    Brand:'Hacking',
    Description:'A hacker is a person skilled in information technology who uses their technical knowledge to achieve a goal or overcome an obstacle.',
    Time: '6 Month',
    Rate: 4.2,
    },
  ]
}